version: '3.7'

services:
    experiment-service:
        container_name: ${CONTAINER}
        image: ${IMAGE}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOME: ${EAPP}
        volumes:
        - '${APP}:${EAPP}'
        - '${DATA}:${EDATA}'
        command: python run_partially_experiments.py